\input texinfo
@documentencoding UTF-8

@ifnottex
@paragraphindent 0
@end ifnottex
@node Top
@top Top

@menu
* Org Readme::
@end menu

@node Org Readme
@chapter Org Readme
Matthew L. Fidler ## Library Information @strong{org-readme.el} --- Integrates Readme.org and Commentary/Change-logs.

@itemize
@item
@strong{Filename} -- org-readme.el
@item
@strong{Description} -- Integrate Readme.org and Commentary/Change Logs.
@item
@strong{Author} -- Matthew L. Fidler
@item
@strong{Maintainer} -- Matthew L. Fidler
@item
@strong{Created} -- Fri Aug 3 22:33:41 2012 (-0500)
@item
@strong{Version} -- 0.24
@item
@strong{Package-Requires} -- ((http-post-simple "1.0") (yaoddmuse "0.1.1")(header2 "21.0") (lib-requires "21.0"))
@item
@strong{Last-Updated} -- Mon Aug 20 22:17:18 2012 (-0500)
@item
@strong{By} -- Matthew L. Fidler
@item
@strong{Update #} -- 751
@item
@strong{URL} -- https:__github.com_mlf176f2_org-readme
@item
@strong{Keywords} -- Header2@comma{} Readme.org@comma{} Emacswiki@comma{} Git
@item
@strong{Compatibility} -- Tested with Emacs 24.1 on Windows.
@end itemize

@menu
* Possible Dependencies::
* Using org-readme::
* Functions::
* History::
@end menu

@node Possible Dependencies
@section Possible Dependencies
None

@node Using org-readme
@section Using org-readme
Org readme is used to:

@itemize
@item
Create/Update a "History" section in the Readme.org based on the changelog section of the Emacs Log.
@item
Create/Update a "Library Information" Section Based on the Emacs lisp header.
@item
Create/Update a "Possible Dependencies" Section Based on the Emacs lisp header.
@end itemize

All other sections of the Readme.org are then put into the "Commentary" section of the readme.org.

In addition this library defines @code{org-readme-sync}@comma{} a convenience function that:

@itemize
@item
Asks for a commentary about the library change.
@item
Syncs the Readme.org with the lisp file as described above.
@item
Updates emacswiki with the library description and the library itself (requires yaoddmuse).
@item
Updates Marmalade-repo if the library version is different than the version in the server (requires http-post-simple).
@item
Updates the git repository with the differences that you posted.
@item
If you are using github@comma{} this library creates a melpa recipie.
@item
If you are using github@comma{} this library creates a el-get recipie.
@end itemize

When @code{org-readme-sync} is called in a @code{Readme.org} file that is not a single lisp file@comma{} the function exports the readme in EmacsWiki format and posts it to the EmacsWiki. ### EmacsWiki Page Names EmacsWiki Page names are generated from the file. @code{org-readme.el} would generate a page of OrgReadme.
@menu
* Why each required library is needed::
@end menu

@node Why each required library is needed
@subsection Why each required library is needed
There are a few required libraries. This is a list of the require libraries and why they are needed.

@multitable @columnfractions 0.26 0.54 
@item 
Library
 @tab Why it is needed
@item 
yaoddmuse http-post-simple header2 lib-requires
 @tab Publish to emacswiki Publish to marmalade-repo.org To create header and changelog To generate the library dependencies
@end multitable

@node Functions
@section Functions
@menu
* Interactive Functions::
* Internal Variables::
@end menu

@node Interactive Functions
@subsection Interactive Functions
@menu
* org-readme-changelog-to-readme::
* org-readme-to-commentary::
* org-readme-buffer-version::
* org-readme-build-el-get-recipe::
* org-readme-build-markdown::
* org-readme-build-melpa-recipe::
* org-readme-build-texi::
* org-readme-default-template::
* org-readme-marmalade-server::
* org-readme-marmalade-token::
* org-readme-marmalade-user-name::
* org-readme-remove-sections::
* org-readme-sync-emacswiki::
* org-readme-sync-git::
* org-readme-sync-marmalade::
* org-readme-use-pandoc-markdown::
@end menu

@node org-readme-changelog-to-readme
@subsubsection org-readme-changelog-to-readme
@code{(org-readme-changelog-to-readme)}

This puts the emacs lisp change-log into the Readme.org file. #### org-readme-convert-to-emacswiki @code{(org-readme-convert-to-emacswiki)}

Converts Readme.org to oddmuse markup and uploads to emacswiki. #### org-readme-convert-to-markdown @code{(org-readme-convert-to-markdown)}

Converts Readme.org to markdown Readme.md. #### org-readme-edit @code{(org-readme-edit)}

Edit change comment for commit. #### org-readme-edit-cancel @code{(org-readme-edit-cancel)}

Cancel the edit log. #### org-readme-edit-commit @code{(org-readme-edit-commit)}

Changelog for editing. #### org-readme-git @code{(org-readme-git)}

Add The files to git. #### org-readme-insert-variables @code{(org-readme-insert-variables)}

Extracts variable documentation and places it in the Readme.org file. #### org-readme-marmalade-post @code{(org-readme-marmalade-post)}

Posts the current buffer to Marmalade. #### org-readme-sync @code{(org-readme-sync &optional COMMENT-ADDED)}

Syncs Readme.org with current buffer. When COMMENT-ADDED is non-nil@comma{} the comment has been added and the syncing should begin.

@node org-readme-to-commentary
@subsubsection org-readme-to-commentary
@code{(org-readme-to-commentary)}

Change Readme.org to a Commentary section. #### org-readme-top-header-to-readme @code{(org-readme-top-header-to-readme)}

This puts the top header into the Readme.org file as Library Information ### Internal Functions

@node org-readme-buffer-version
@subsubsection org-readme-buffer-version
@code{(org-readme-buffer-version)}

Gets the version of the current buffer. #### org-readme-build-el-get @code{(org-readme-build-el-get)}

Builds an el-get recipe. This assumes github@comma{} though others could be added. Returns file name if created. #### org-readme-build-melpa @code{(org-readme-build-melpa)}

Builds a melpa recipe. This assumes github@comma{} though other could be added. Returns file name if created. #### org-readme-find-readme @code{(org-readme-find-readme)}

Find the Readme.org. #### org-readme-get-change @code{(org-readme-get-change)}

Get file for changelog commits. #### org-readme-get-emacswiki-name @code{(org-readme-get-emacswiki-name)}

Gets emacswiki-style name based on buffer. #### org-readme-in-readme-org-p @code{(org-readme-in-readme-org-p)}

Determine if the currently open buffer is the Readme.org #### org-readme-insert-functions @code{(org-readme-insert-functions)}

Extracts function documentation and places it in the Readme.org file. #### org-readme-marmalade-version @code{(org-readme-marmalade-version PACKAGE)}

Gets the marmalade version of the PACKAGE. #### org-readme-remove-section =(org-readme-remove-section SECTION &optional TXT ANY-LEVEL AT-BEGINNING)=

Remove @code{org-mode} SECTION. Optionally insert TXT. When ANY-LEVEL is non-nil@comma{} any level may be specified. When AT-BEGINNING is non-nil@comma{} if the section is not found@comma{} insert it at the beginning. #### org-readme-single-lisp-p @code{(org-readme-single-lisp-p)}

Determine if the Readme.org is in a directory with a single lisp file. If so@comma{} return the name of that lisp file@comma{} otherwise return nil. #### org-readme-token @code{(org-readme-token)}

Gets marmalade-token@comma{} if not already saved.* Variables ### Customizable Variables

@node org-readme-build-el-get-recipe
@subsubsection org-readme-build-el-get-recipe
Builds a el-get recipe based on github information

@node org-readme-build-markdown
@subsubsection org-readme-build-markdown
Builds Readme.md from Readme.org

@node org-readme-build-melpa-recipe
@subsubsection org-readme-build-melpa-recipe
Builds a melpa recipe based on github information

@node org-readme-build-texi
@subsubsection org-readme-build-texi
Builds library-name.texi from Readme.org@comma{} using Readme.md and pandoc. Requires @code{org-readme-build-markdown} to be non-nil as pandoc to be found.

@node org-readme-default-template
@subsubsection org-readme-default-template
Default template for blank Readme.org Files. LIB-NAME is replaced with the library.

@node org-readme-marmalade-server
@subsubsection org-readme-marmalade-server
Marmalade server website. This should start with http: and should notend with a trailing forward slash@comma{} just like the default value of http:__marmalade-repo.org

@node org-readme-marmalade-token
@subsubsection org-readme-marmalade-token
Marmalade token to upload content to the marmalade server.

@node org-readme-marmalade-user-name
@subsubsection org-readme-marmalade-user-name
Marmalade user name to upload content to the marmalade server.

@node org-readme-remove-sections
@subsubsection org-readme-remove-sections
List of sections to remove when changing the Readme.org to Change-log.

@node org-readme-sync-emacswiki
@subsubsection org-readme-sync-emacswiki
Posts library to the emacswiki. Requires @code{yaoddmuse}

@node org-readme-sync-git
@subsubsection org-readme-sync-git
Posts library to git

@node org-readme-sync-marmalade
@subsubsection org-readme-sync-marmalade
Posts library to marmalade-repo.org

@node org-readme-use-pandoc-markdown
@subsubsection org-readme-use-pandoc-markdown
Uses pandoc's grid tables instead of transferring the tables to html.

@node Internal Variables
@subsection Internal Variables
@menu
* org-readme-edit-mode-map::
@end menu

@node org-readme-edit-mode-map
@subsubsection org-readme-edit-mode-map
Keymap for editing change-logs.

Value: (keymap (24 keymap (19 . org-readme-edit-commit)) (3 keymap (11 . org-readme-edit-cancel) (3 . org-readme-edit-commit)) keymap (27 keymap (9 . ispell-complete-word)))

@node History
@section History
@itemize
@item
@strong{20-Aug-2012} -- Attempt to remove Readme.md when not needed. (Matthew L. Fidler)
@item
@strong{20-Aug-2012} -- Added ability to add function documentation and variable documentation to the Readme.org file (Matthew L. Fidler)
@item
@strong{20-Aug-2012} -- Added pandoc markdown table support (optional) (Matthew L. Fidler)
@item
@strong{13-Aug-2012} -- Another attempt to make texinfo documents. (Matthew L. Fidler)
@item
@strong{13-Aug-2012} -- Added texinfo output. Allows native emacs documentation. (Matthew L. Fidler)
@item
@strong{13-Aug-2012} -- Tried to post behind firewall. Reattempting. (Matthew L. Fidler)
@item
@strong{13-Aug-2012} -- Changed the @code{org-readme-remove-section} to use @code{org-cut-subtree}. Hopefully all errors will resolve themselves now. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Reverted. Still buggy. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Another attempt at bug fix to remove section. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Another attempt at a remove-section fix. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Bug fix for org-readme version tagging. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Test the bug where some of the section text is deleted (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Added more documentation (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- One last bug fix to the markdown export engine. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Markdown bug fix (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Bug fix for el-get recipe. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Added the ability to create a markdown Readme (Readme.md) as well as adding a el-get recipe. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Bug fix for emacswiki post and melpa bug fix (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Bug fix for adding melpa recipes. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Bug fix for creating melpa recipe. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Added ability to add melpa recipe (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Bug fix for pushing tags to a git repository (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Another fix for git tags. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Found a bug@comma{} let see if tagging works now. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Added Git tagging of new versions. Lets see if it works. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Git push worked. Bumping minor version. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Attempted to push repository again. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Attempt to push with git. Something changed. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Added better Package-Requires tag. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Made request for minor revision earlier@comma{} and fixed bug. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Fixed code typo (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Bug fix for deleting a section of a Readme.org file. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Testing bug. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Minor bug fix. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Bug fix for comment sync@comma{} now Readme.org @code{file} is translated to lisp @code{file}. Additionally@comma{} asks for version bump. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Bug fix for syncing readme. Now the returns should not be as prevalent. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Attempting to post to marmlade again... (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Attempting to fix org-readme-marmalade-post. (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Bug fix to upload to emacswiki and upload to marmalade-repo (Matthew L. Fidler)
@item
@strong{11-Aug-2012} -- Added marmalade-repo support. Now org-readme should upload to marmalade-repo when the version is different from the latest version. (Matthew L. Fidler)
@item
@strong{08-Aug-2012} -- Fixed preformatting tags in emacswiki post. Previously they may have been replaced with
<_pre> instead of
<_pre>. This makes the emacswiki page display correctly. (Matthew L. Fidler)
@item
@strong{07-Aug-2012} -- To use@comma{} put (require 'ess-smart-underscore) in your ~/.emacs file 7-Aug-2012 Matthew L. Fidler Last-Updated: Mon Aug 20 22:18:10 2012 (-0500)
@item
@strong{06-Aug-2012} -- Added support for uploading Readme.org files to emacswiki without having to have a single associated lisp file. (Matthew L. Fidler)
@item
@strong{06-Aug-2012} -- Bug fix for syncing from the single lisp file. (Matthew L. Fidler)
@item
@strong{06-Aug-2012} -- Added the ability to call @code{org-readme-sync} from Readme.org (Matthew L. Fidler)
@item
@strong{05-Aug-2012} -- Added git pushing to org-readme (Matthew L. Fidler)
@item
@strong{05-Aug-2012} -- Added git support as well as a comment mode. The only thing that should need to be called is @code{org-readme-sync} (Matthew L. Fidler)
@item
@strong{04-Aug-2012} -- Added syncing with emacswiki. (Matthew L. Fidler)
@item
@strong{04-Aug-2012} -- Initial Release (Matthew L. Fidler)* Variables ### Customizable Variables
@end itemize

@menu
* Internal Variables::
@end menu

@node org-readme-build-el-get-recipe
@subsubsection org-readme-build-el-get-recipe
Builds a el-get recipe based on github information

@node org-readme-build-markdown
@subsubsection org-readme-build-markdown
Builds Readme.md from Readme.org

@node org-readme-build-melpa-recipe
@subsubsection org-readme-build-melpa-recipe
Builds a melpa recipe based on github information

@node org-readme-build-texi
@subsubsection org-readme-build-texi
Builds library-name.texi from Readme.org@comma{} using Readme.md and pandoc. Requires @code{org-readme-build-markdown} to be non-nil as pandoc to be found.

@node org-readme-default-template
@subsubsection org-readme-default-template
Default template for blank Readme.org Files. LIB-NAME is replaced with the library.

@node org-readme-drop-markdown-after-build-texi
@subsubsection org-readme-drop-markdown-after-build-texi
Removes Readme.md after texinfo is generated

@node org-readme-marmalade-server
@subsubsection org-readme-marmalade-server
Marmalade server website. This should start with http: and should notend with a trailing forward slash@comma{} just like the default value of http:__marmalade-repo.org

@node org-readme-marmalade-token
@subsubsection org-readme-marmalade-token
Marmalade token to upload content to the marmalade server.

@node org-readme-marmalade-user-name
@subsubsection org-readme-marmalade-user-name
Marmalade user name to upload content to the marmalade server.

@node org-readme-remove-sections
@subsubsection org-readme-remove-sections
List of sections to remove when changing the Readme.org to Change-log.

@node org-readme-sync-emacswiki
@subsubsection org-readme-sync-emacswiki
Posts library to the emacswiki. Requires @code{yaoddmuse}

@node org-readme-sync-git
@subsubsection org-readme-sync-git
Posts library to git

@node org-readme-sync-marmalade
@subsubsection org-readme-sync-marmalade
Posts library to marmalade-repo.org

@node org-readme-use-pandoc-markdown
@subsubsection org-readme-use-pandoc-markdown
Uses pandoc's grid tables instead of transferring the tables to html.

@node Internal Variables
@subsection Internal Variables
@menu
* org-readme-edit-mode-map::
@end menu

@node org-readme-edit-mode-map
@subsubsection org-readme-edit-mode-map
Keymap for editing change-logs.

Value: (keymap (24 keymap (19 . org-readme-edit-commit)) (3 keymap (11 . org-readme-edit-cancel) (3 . org-readme-edit-commit)) keymap (27 keymap (9 . ispell-complete-word)))

@bye
