#+TITLE: Org Readme
#+AUTHOR: Matthew L. Fidler
* Library Information
 *org-readme.el* --- Integrates Readme.org and Commentary/Change-logs.

 - Filename :: [[file:org-readme.el][org-readme.el]]
 - Description :: Integrate Readme.org and Commentary/Change Logs.
 - Author :: Matthew L. Fidler
 - Maintainer :: Matthew L. Fidler
 - Created :: Fri Aug  3 22:33:41 2012 (-0500)
 - Version :: 0.19
 - Package-Requires :: ((http-post-simple "1.0") (yaoddmuse "0.1.1")(header2 "21.0") (lib-requires "21.0"))
 - Last-Updated :: Sat Aug 11 23:51:56 2012 (-0500)
 -           By :: Matthew L. Fidler
 -     Update # :: 666
 - URL :: https://github.com/mlf176f2/org-readme
 - Keywords :: Header2, Readme.org, Emacswiki, Git
 - Compatibility :: Tested with Emacs 24.1 on Windows.

* Possible Dependencies

  None


* * Library Information
 *org-readme.el* --- Integrates Readme.org and Commentary/Change-logs.

 - Filename :: [[file:org-readme.el][org-readme.el]]
 - Description :: Integrate Readme.org and Commentary/Change Logs.
 - Author :: Matthew L. Fidler
 - Maintainer :: Matthew L. Fidler
 - Created :: Fri Aug  3 22:33:41 2012 (-0500)
 - Version :: 0.18
 - Package-Requires :: ((http-post-simple "1.0") (yaoddmuse "0.1.1")(header2 "21.0") (lib-requires "21.0"))
 - Last-Updated :: Sat Aug 11 17:13:51 2012 (-0500)
 -           By :: Matthew L. Fidler
 -     Update # :: 660
 - URL :: https://github.com/mlf176f2/org-readme
 - Keywords :: Header2, Readme.org, Emacswiki, Git
 - Compatibility :: Tested with Emacs 24.1 on Windows.

* History

 - 11-Aug-2012 ::  Reverted. Still buggy. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Another attempt at bug fix to remove section. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Another attempt at a remove-section fix. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Bug fix for org-readme version tagging. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Test the bug where some of the section text is deleted  (Matthew L. Fidler)
 - 11-Aug-2012 ::  Added more documentation (Matthew L. Fidler)
 - 11-Aug-2012 ::  One last bug fix to the markdown export engine. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Markdown bug fix (Matthew L. Fidler)
 - 11-Aug-2012 ::  Bug fix for el-get recipe. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Added the ability to create a markdown Readme (Readme.md) as well as adding a el-get recipe. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Bug fix for emacswiki post and melpa bug fix (Matthew L. Fidler)
 - 11-Aug-2012 ::  Bug fix for adding melpa recipes.  (Matthew L. Fidler)
 - 11-Aug-2012 ::  Bug fix for creating melpa recipe. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Added ability to add melpa recipe (Matthew L. Fidler)
 - 11-Aug-2012 ::  Bug fix for pushing tags to a git repository (Matthew L. Fidler)
 - 11-Aug-2012 ::  Another fix for git tags. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Found a bug, let see if tagging works now. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Added Git tagging of new versions. Lets see if it works. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Git push worked. Bumping minor version. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Attempted to push repository again. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Attempt to push with git. Something changed. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Added better Package-Requires tag. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Made request for minor revision earlier, and fixed bug. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Fixed code typo (Matthew L. Fidler)
 - 11-Aug-2012 ::  Bug fix for deleting a section of a Readme.org file. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Testing bug. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Minor bug fix. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Bug fix for comment sync, now Readme.org =file= is translated to lisp =file=. Additionally, asks for version bump. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Bug fix for syncing readme. Now the returns should not be as prevalent. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Attempting to post to marmlade again... (Matthew L. Fidler)
 - 11-Aug-2012 ::  Attempting to fix org-readme-marmalade-post. (Matthew L. Fidler)
 - 11-Aug-2012 ::  Bug fix to upload to emacswiki and upload to marmalade-repo (Matthew L. Fidler)
 - 11-Aug-2012 ::  Added marmalade-repo support. Now org-readme should upload to marmalade-repo when the version is different from the latest version. (Matthew L. Fidler)
 - 08-Aug-2012 ::  Fixed preformatting tags in emacswiki post. Previously they may have been replaced with <PRE></pre> instead of <pre></pre>. This makes the emacswiki page display correctly. (Matthew L. Fidler)
 - 07-Aug-2012 ::  To use, put (require 'ess-smart-underscore) in your ~/.emacs file 7-Aug-2012 Matthew L. Fidler Last-Updated: Sat Aug 11 23:52:09 2012 (-0500)
 - 06-Aug-2012 ::  Added support for uploading Readme.org files to emacswiki without having to have a single associated lisp file. (Matthew L. Fidler)
 - 06-Aug-2012 ::  Bug fix for syncing from the single lisp file. (Matthew L. Fidler)
 - 06-Aug-2012 ::  Added the ability to call =org-readme-sync= from Readme.org (Matthew L. Fidler)
 - 05-Aug-2012 ::  Added git pushing to org-readme (Matthew L. Fidler)
 - 05-Aug-2012 ::  Added git support as well as a comment mode. The only thing that should need to be called is =org-readme-sync= (Matthew L. Fidler)
 - 04-Aug-2012 ::  Added syncing with emacswiki.  (Matthew L. Fidler)
  - 04-Aug-2012 ::  Initial Release  (Matthew L. Fidler)
